export type ReportParams = {
  MajorToken: string;
  MinorToken: string;
  IMEIs: string[];
  Emails: string[];
  Export: "PDF";
  Logo: string;
  DateFrom?: string;
  DateTo?: string;
  To: string;
  From: string;
  AlertIds?: string[];
  Alerts?: string[];
  AsIds?: string[];
  Features?: string[];
  GetGeofenceCodes?: string[];
  EventClass?: string;
  EventTypes?: number[] | string;
  EventDurations?: string[];
};
