export const Constants = {
  MOMENT_API_DATE_FORMAT: "YYYY-MM-DD HH:mm:ss",
  MOMENT_DATE_TIME_FORMAT: "YYYY-MM-DD HH:mm",
  MOMENT_TIME_FORMAT: "h:mm a",
  MOMENT_TIMEFORMAT4: "YYYY-MM-DD",
  BOTTOM_SHEET_SNAP_POINTS: [0.3, 0.65, 0.87],
};
