export const Constants = {
  MOMENT_API_DATE_FORMAT: "YYYY-MM-DD HH:mm:ss",
  MOMENT_DATE_TIME_FORMAT: "YYYY-MM-DD HH:mm",
  MOMENT_TIME_FORMAT: "h:mm a",
  MOMENT_TIMEFORMAT4: "YYYY-MM-DD",
  BOTTOM_SHEET_SNAP_POINTS: [0.3, 0.65, 0.87],
  PLAYBACK_EVENTS: [
    { id: "1", name: "Ignition On" },
    { id: "2", name: "Stopped" },
    { id: "3", name: "Enter Geofence" },
    { id: "4", name: "Leave Geofence" },
    { id: "5", name: "All Other Alarms" },
  ],
  POSITION_ALERTS: {
    None: { id: 0, name: "None" },
    Custom: { id: 1, name: "Custom" },
    SOS: { id: 2, name: "SOS" },
    ElectricCutoff: { id: 4, name: "Electric Cutoff" },
    InGeoFance: { id: 8, name: "In GeoFance" },
    OutGeoFance: { id: 16, name: "Out GeoFance" },
    HighSpeed: { id: 32, name: "High Speed" },
    LowSpeed: { id: 64, name: "Low Speed" },
    Theft: { id: 128, name: "Theft" },
    Vibrate: { id: 256, name: "Vibrate" },
    LowPower: { id: 512, name: "Low Power" },
    Moving: { id: 1024, name: "Moving" },
    Fire: { id: 2048, name: "Fire" },
    MedicalHelp: { id: 4096, name: "Medical Help" },
    Defence: { id: 8192, name: "Defence" },
    Destroy: { id: 16384, name: "Destroy" },
    ACCON: { id: 32768, name: "ACC On" },
    ACCOFF: { id: 65536, name: "ACC Off" },
    INPUT1: { id: 131072, name: "Input 1 On" },
    INPUT2: { id: 262144, name: "Input 2 On" },
    INPUT1_LOW: { id: 524288, name: "Input 1 Low" },
    INPUT2_LOW: { id: 1048576, name: "Input 2 Low" },
    HardBrake: { id: 2097152, name: "Hard Brake" },
    LowTemp: { id: 4194304, name: "Low Temperature" },
    HighTemp: { id: 8388608, name: "High Temperature" },
    FatigueDriving: { id: 16777216, name: "Fatigue Driving" },
    Accelerate: { id: 33554432, name: "Accelerate" },
    Offline: { id: 67108864, name: "Offline" },
    INPUT3: { id: 134217728, name: "Input 3 On" },
    INPUT3_OFF: { id: 268435456, name: "Input 3 Off" },
    INPUT4: { id: 536870912, name: "Input 4 On" },
    INPUT4_OFF: { id: 1073741824, name: "Input 4 Off" },
  },
};

export const EventIcons = {
  general: require("../assets/markers/pin-activity.png"),
  accOff: require("../assets/markers/pin-acc-off.png"),
  accOn: require("../assets/markers/pin-acc-on.png"),
  geoIn: require("../assets/markers/pin-geo-in.png"),
  geoOut: require("../assets/markers/pin-geo-out.png"),
  moving: require("../assets/markers/pin-moving.png"),
  stopped: require("../assets/markers/pin-stopped.png"),
};
